env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: moudle
plugins:
  - '@typescript-eslint'
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - never
  '@typescript-eslint/no-non-null-assertion':
    - off
